# Generated by Django 5.2 on 2025-04-19 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_api', '0003_conversation_lawyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='knowledge_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='rag_api.knowledgebase'),
        ),
    ]
