# Generated by Django 5.2 on 2025-04-19 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_api', '0004_alter_document_knowledge_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='knowledge_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='rag_api.knowledgebase'),
        ),
    ]
